### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by sirinath** [ibmruntimes/Semeru-Runtimes#12]
Please open source the infrastructure, process, testing and distribution.

**Comment by mstoodle** [comment]
IBM is vendor who produces a JDK, just like a dozen other vendors (very few of which are even as open as we are, I would hazard to guess). We do as much as we can afford to do in the open, @sirinath .

We already contributed to and use at GitHub:
- https://github.com/ibmruntimes/ci-jenkins-pipelines
- https://github.com/ibmruntimes/semeru-containers
- https://github.com/ibmruntimes/temurin-build

We run all the open source AQA testing from Adoptium.

If you have a more specific request, you can always reopen to ask. We try hard to do whatever we can in the open, but please recognize that we aren't always at liberty to open source everything (like those steps we need to perform due to internal IBM release processes, for example).

**Comment by sirinath** [comment]
Since OpenJ9 was moved out of Adoptium / AdoptOpenJDK, is there and true or equivalent replacement? My concern is 
Semeru builds might not be as open as it once was when OpenJ9 was included in AdoptOpenJDK.

**Comment by pshipton** [comment]
The Semeru Open Edition builds are 100% open source, built from the following open source repos. The -version output shows the open source git SHAs used to do the build.

https://github.com/eclipse-openj9/openj9
https://github.com/eclipse-openj9/openj9-omr
https://github.com/ibmruntimes/openj9-openjdk-jdk8
https://github.com/ibmruntimes/openj9-openjdk-jdk11
https://github.com/ibmruntimes/openj9-openjdk-jdk17

**Comment by mstoodle** [comment]
> My concern is Semeru builds might not be as open as it once was when OpenJ9 was included in AdoptOpenJDK.
 
As we've described in this issue and in other forums, IBM builds Semeru Runtimes (at no cost to anyone, though I hope you realize there are nontrivial financial costs and effort associated with us doing it) from open source projects. The Open Edition binaries continue to be licensed via an open source license: **GPLv2+Classpath Exception.**

Do you have a specific concern? What "might not be as open" thing are you worried about and do you have a specific concern with it not being "as" open? We're doing our best to be transparent here, but if you have a specific real concern that we can alleviate, we can try to find a way to do so.

**Comment by sirinath** [comment]
If for some reason IBM stops building and distributing The Open Edition binaries is there an community or organisation to take over the whole process. If this was make part of a foundation this risk is mitigated.

I know the sources and available and developed in the open. But I believe building and testing the binaries from the sources through open is non trivial . So if building and testing is also backed by a foundation then availability would be more sure than now.

**Comment by mstoodle** [comment]
AdoptOpenJDK wan't just about producing binaries, although that's the front face people are most familiar with. AdoptOpenJDK is a community that develops scripts and infra to build, test, package, and install JDK binaries based on open source software at OpenJDK and Eclipse OpenJ9.

Eclipse Adoptium continues to develop and make available scripts for building and testing and packaging and installing JDKs that include Eclipse OpenJ9. Members of the Eclipse OpenJ9 community continue to work there. IBM employees continue to work there, along with a lot of other vendors' employees and a lot of amazing volunteers. There continues to be a community effort supporting the creation of JDK binaries based on OpenJDK, including Eclipse OpenJ9 based JDK binaries. It's just that this community is no longer legally allowed to produce JDK binaries with OpenJ9 themselves since it moved to a foundation.

The Eclipse Foundation entered into an agreement that prevents them or their projects from marketing, promoting, or distributing OpenJ9 based JDK binaries unless they have been TCK certified (and Oracle, to my knowledge, does not make available anything but commercial licenses to run the Java SE TCK on OpenJ9). So IBM picked up that part by creating IBM Semeru Runtimes. IBM isn't doing anything to produce the Open Edition binaries that another company or community couldn't do, other than stamping IBM's name and versioning on them. Just like other JDK vendors are "just" building OpenJDK themselves (like any other vendor can do), in some cases even using the same Adoptium scripts that IBM uses to build Semeru Runtimes.

Does that help with your concern at all?

**Comment by sirinath** [comment]
Since Eclipse Adoptium is not legally allowed to distribute OpenJ9 why not create a sister project specifically for OpenJ9. IBM can distribute and support the binaries from this project like what was done in AdopOpenJDK days.

Does IBM have a Java SE TCK? Is it independently developed or licensed from Oracle?

**Comment by sirinath** [comment]
Since Eclipse Adoptium is not legally allowed to distribute OpenJ9 why not create a sister project specifically for OpenJ9. IBM can distribute and support the binaries from this project like what was done in AdopOpenJDK days.

Does IBM have a Java SE TCK? Is it independently developed or licensed from Oracle?
