### ISSUE TITLE
Java 19 builds

### ISSUE THREAD

**Issue by FireMasterK** [ibmruntimes/Semeru-Runtimes#50]
Title,

Will these be made available?

Could we have docker images for them too?

**Comment by AdamBrousseau** [comment]
I don't believe there is a definitive answer on whether OpenJ9 will GA a jdk19 level. The intention and hope is to release it before the April CPU security updates. IBM is currently producing Milestone builds as we work towards GA. If we release a GA we will also create containers on DockerHub and IBM Container Registry.

 Here is the OpenJ9 Milestone plan for the release
 https://github.com/eclipse-openj9/openj9/milestone/35
 
 I'm not sure I can say much more than that but one of the dev leads may chime in.

**Comment by AdamBrousseau** [comment]
Yes, jdk19 eol aligns with the jdk20 release date as it is a short term release. OpenJ9 (likely) won't produce any 19 releases after 19.0.2 is GA. I believe there is still value in OpenJ9 and IBM Semeru delivering jdk19 after March 21. I'm not sure what commercial support offerings there are for short term releases (cc @mstoodle ).

**Comment by mstoodle** [comment]
We would not extend commercial support beyond the usual dates without significant demand which I don't think would materialize even for Java 19, but I think there's value in producing the binary release for 19 so people have something to evaluate, so long as it doesn't interfere too much in delivering Java 20 (i.e. I wouldn't want to make Java 20 substantially later just so that we delivered a late Java 19), in particular because the later 20 releases, the more impact we're likely to see in Java 21 release date. That's the trade-off and "snowball" issues we're trying to manage now.

**Comment by rdean** [comment]
Speaking for myself, I'm much more interested in Java 20 at this point, but more generally I'm hoping that IBM establishes a process that allows Semeru to be GA'd as close to the upstream OpenJDK GA as possible.

**Comment by AdamBrousseau** [comment]
We released 19.0.2 earlier this week.
Docker images should be up next week on IBM Container Registry and DockerHub.
https://developer.ibm.com/languages/java/semeru-runtimes/downloads/?version=19
